### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/MCCTeam.github.io#12]
# TODO
- [x] Add Farmer Bot
- [x] Add Enchanting
- [x] Update the command line usage to reflect TOML changes and add examples.
- [x] Add `blockinfo` command
