### ISSUE TITLE
Phase 2

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/MCCTeam.github.io#6]
## Tasks for Phase 2
- [ ] FAQ Section
- [x] How to run the MCC on a VPS
- [x] How to run the MCC on an Android phone
- [ ] ChatBot API page generator
- [ ]  Youtube tutorials (Will take some time)
   - [ ] About MCC and basic usage
   - [ ] Installation on Windows
   - [ ] Installation on Linux
   - [ ] Installation on Mac
   - [ ] Installation using Docker
   - [ ] Installation on an VPS
   - [ ] Installation on an Android phone
   - [ ] Configuration and usage
   - [ ] Chat Bots and usage
   - [ ] Making Chat Bots
   - [ ] Contributing (Code walk-through with Wiki.vg examples)

## Optional when merged
- [ ] Websocket API and protocol
- [ ] JavaScript Library API, tutorial and examples (This might be a separate documentation project, just linked in the main documentation)

## Notes
- Add examples for `config/chatbots` in FAQ section once it's done and reference those chat bots in the Chat Bots section.
