### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/MCCTeam.github.io#8]
Done:
 - [x] Update the documentation for `AutoRespond`
 - [x] Add `/execif`
 - [x] Add `/execmulti`
 - [x] Add a link to .NET Core 6 installation for ARM 64 systems in the Running on VPS section
 - [x] Fix the supported versions for Inventory Handling warnings in the `Usage` section and [here](https://mccteam.github.io/guide/#notes-on-some-features)
 - [x] Use quote styling for [this](https://mccteam.github.io/guide/installation.html#installation-1) warning
 - [x] Remove the Docker warning from [here](https://mccteam.github.io/guide/#notes-on-some-features)
 - [x] Add a warning for AWS users and a suggestion to use a Proxy
 - [x] When installing .NET Core 6 on Ubuntu 22.04 with newer versions an issue could appear, add a reference to [this](https://github.com/dotnet/sdk/issues/27082#issuecomment-1211143446) as a solution
 - [x] Add a NOTE for when logging in on AWS, to wait for a min or two
 - [x] Add a NOTE on Screen when installing on linux, to use tmux instead if having issues

TODO:
 - [x] Update the inventory command documentation
 - [x] Add the `/bots` and `/reload` commands documentation
 - [x] Add the reference for random intervals for Script Scheduler
 - [x] Add Map Chat Bot to the documentation ~~when merged~~
 - [x] Fix Digital Ocean typo in the Run on VPS section
 - [x] Add documentation for `/bed` and update the documentation for `/dig` with relative command examples
 - [x] Update the documentation for Anti AFK
